apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jyl4z4dol-python 
  janus-idp.io/tekton: jyl4z4dol-python
  backstage.io/kubernetes-id: jyl4z4dol-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jyl4z4dol-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  