apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jyl4z4dol-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jyl4z4dol-python 
  name: jyl4z4dol-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jyl4z4dol-python 
